In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5890, 4658, 2254, 4986],
 [5890, 4658, 2254, 4974],
 [5890, 9052, 2254, 6971],
 [1924, 6310, 1602, 2086, 2518],
 [1924, 6310, 1602, 2086, 4498],
 [956, 5890, 1772, 2254, 4267],
 [5339, 9992, 3561, 2086]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5890 4658 2254 4986]
 [   0    0    0    0 5890 4658 2254 4974]
 [   0    0    0    0 5890 9052 2254 6971]
 [   0    0    0 1924 6310 1602 2086 2518]
 [   0    0    0 1924 6310 1602 2086 4498]
 [   0    0    0  956 5890 1772 2254 4267]
 [   0    0    0    0 5339 9992 3561 2086]]


In [10]:
## feature representation
dim=10

In [ ]:
from keras.models import Sequential
from keras.layers import Input, Embedding, SimpleRNN, Dense


In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_shape=(sent_length,)))
model.compile('adam','mse')

c:\Users\tejas\AI-ML Gen AI Projects\mlenv\lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step


array([[[ 0.02332279,  0.01996796,  0.01072813, -0.02008796,
         -0.04471632, -0.00507919, -0.02449284, -0.04278004,
         -0.0372875 , -0.0174192 ],
        [ 0.02332279,  0.01996796,  0.01072813, -0.02008796,
         -0.04471632, -0.00507919, -0.02449284, -0.04278004,
         -0.0372875 , -0.0174192 ],
        [ 0.02332279,  0.01996796,  0.01072813, -0.02008796,
         -0.04471632, -0.00507919, -0.02449284, -0.04278004,
         -0.0372875 , -0.0174192 ],
        [ 0.02332279,  0.01996796,  0.01072813, -0.02008796,
         -0.04471632, -0.00507919, -0.02449284, -0.04278004,
         -0.0372875 , -0.0174192 ],
        [-0.00079757,  0.02706709, -0.02243725, -0.0295439 ,
         -0.00487105,  0.0022723 , -0.01789358,  0.03610686,
         -0.0231799 ,  0.02613468],
        [ 0.02086471, -0.02606349,  0.00850704,  0.00163534,
          0.03736398,  0.03916268, -0.03709813,  0.02769336,
         -0.04687318, -0.04062365],
        [ 0.0360433 ,  0.04686253, -0.02184384, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 5890, 4658, 2254, 4986], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None